build:
  image: "klakegg/hugo:0.93.2-ci"
  only:
    - main
  script:
    - echo "Building project..."
    - hugo --minify
    - find public/js/ -type f ! -name '*.min.js' -delete
    - find public/css/ -type f ! -name '*.min.css' -delete
  artifacts:
    paths:
      - public

deploy-testing:
  needs: [build]
  environment: testing
  image:
    name: amazon/aws-cli:latest
    entrypoint: ["/bin/bash", "-c"]
  only:
    - main
  script:
    - find ./ -type f -exec sed -i "s/style.css/style.css?$CI_COMMIT_SHORT_SHA/gI" {} \;
    - chmod +x deploy.sh
    - ./deploy.sh

deploy-production:
  needs: [build]
  environment: production
  image:
    name: amazon/aws-cli:latest
    entrypoint: ["/bin/bash", "-c"]
  only:
    - main
  script:
    - find ./ -type f -exec sed -i "s/style.css/style.css?$CI_COMMIT_SHORT_SHA/gI" {} \;
    - chmod +x deploy.sh
    - ./deploy.sh
  when: manual
