baseURL: https://trebehome.github.io/recorder/
languageCode: es
defaultContentLanguage: es
defaultContentLanguageInSubdir: true
title: Demos | TREBE Language Technologies S.L.
assetDir: static
languages:
  es:
    contentDir: content/es
    languageName: es
    weight: 1
  eu:
    contentDir: content/eu
    languageName: eu
    weight: 2
  en:
    contentDir: content/en
    languageName: en
    weight: 3
  ca:
    contentDir: content/ca
    languageName: ca
    weight: 4
  gl:
    contentDir: content/gl
    languageName: gl
    weight: 5
